# Generated by Django 3.1 on 2020-08-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
    ]
